// SPDX-License-Identifier: Apache-2.0
import fs from 'node:fs/promises';import path from 'node:path';import {hyperframes,command,environment} from '../src/pipeline/tools.ts';import {digest} from '../src/pipeline/stage-state.ts';
const root=process.cwd(),base=path.join(root,'reports/promo-design-upgrade-v5'),dir=path.join(base,'composition'),visual=path.join(base,'editorial-visuals-v3-52s.mp4'),output=path.join(base,'enhe-studio-editorial-review-v3-60s.mp4'),original=path.join(root,'projects/character-enhe-studio-real-v1/renders/draft.mp4'),env=await environment();const results=[];
if(JSON.parse(await fs.readFile(path.join(base,'layout-qa.json'),'utf8')).status!=='PASS')throw Error('Layout verification required');
const checks=JSON.parse(await fs.readFile(path.join(base,'hyperframes-checks.json'),'utf8'));if(checks.some(r=>r.exitCode!==0))throw Error('HyperFrames checks must pass');
if(await fs.access(output).then(()=>true,()=>false))throw Error('Preserving existing review video; choose an explicit new version');
const run=async(exe,args,timeoutMs=600000)=>{const r=await command(exe,args,{cwd:root,env,timeoutMs});results.push(r);await fs.writeFile(path.join(base,'render-commands.json'),JSON.stringify(results,null,2));if(r.exitCode)throw Error((r.stdout+r.stderr).slice(-3000));return r;};
const htmlSha256=digest(await fs.readFile(path.join(dir,'index.html'))),renderState=path.join(base,'visual-render-state.json');
if(await fs.access(visual).then(()=>true,()=>false)){const frozen=JSON.parse(await fs.readFile(renderState,'utf8'));if(frozen.htmlSha256!==htmlSha256||frozen.visualSha256!==digest(await fs.readFile(visual)))throw Error('Stale visual render cannot be reused');}
if(!await fs.access(visual).then(()=>true,()=>false)){const r=await hyperframes(['render',dir,'--output',visual,'--quality','standard','--fps','30','--workers','2'],dir,600000);results.push(r);await fs.writeFile(path.join(base,'render-commands.json'),JSON.stringify(results,null,2));if(r.exitCode)throw Error(r.stderr);await fs.writeFile(renderState,JSON.stringify({htmlSha256,visualSha256:digest(await fs.readFile(visual))},null,2));console.log('Visual render complete');}
// Preserve source audio packets. Lossless H.264 keeps every decoded author pixel unchanged.
await run(env.HYPERFRAMES_FFMPEG_PATH!,['-v','error','-n','-i',visual,'-i',original,'-filter_complex','[0:v]trim=start_frame=0:end_frame=1560,setpts=PTS-STARTPTS[v0];[1:v]trim=start_frame=1560:end_frame=1800,setpts=PTS-STARTPTS[v1];[v0][v1]concat=n=2:v=1:a=0[out]','-map','[out]','-map','1:a:0','-c:v','libx264','-preset','fast','-qp','0','-pix_fmt','yuv420p','-c:a','copy','-movflags','+faststart',output]);
const probe=await run(env.HYPERFRAMES_FFPROBE_PATH!,['-v','error','-show_streams','-show_format','-of','json',output]),decode=await run(env.HYPERFRAMES_FFMPEG_PATH!,['-v','error','-xerror','-i',output,'-f','null','-']);
const exact=[];for(const input of [original,output]){const frames=await run(env.HYPERFRAMES_FFMPEG_PATH!,['-v','error','-i',input,'-an','-vf','trim=start_frame=1560:end_frame=1800,setpts=PTS-STARTPTS','-f','framemd5','-']),audio=await run(env.HYPERFRAMES_FFMPEG_PATH!,['-v','error','-i',input,'-map','0:a:0','-c:a','copy','-f','hash','-hash','sha256','-']);exact.push({file:input,authorFrames:frames.stdout.split('\n').filter(x=>x&&!x.startsWith('#')).map(x=>x.split(',').at(-1)?.trim()),audioStreamHash:audio.stdout.trim()});}
const media=JSON.parse(probe.stdout),v=media.streams.find(x=>x.codec_type==='video'),authorExact=exact[0].authorFrames.length===240&&JSON.stringify(exact[0].authorFrames)===JSON.stringify(exact[1].authorFrames),audioExact=exact[0].audioStreamHash===exact[1].audioStreamHash;
const pass=v.width===1920&&v.height===1080&&v.avg_frame_rate==='30/1'&&Number(v.nb_frames)===1800&&Math.abs(Number(media.format.duration)-60)<.04&&authorExact&&audioExact&&!decode.stderr.trim();
await fs.writeFile(path.join(base,'media-qa.json'),JSON.stringify({status:pass?'PASS':'FAIL',output,sha256:digest(await fs.readFile(output)),media,authorExact,audioExact,exact,decode:decode.exitCode},null,2));
for(const t of [2.3,5.75,11.2,16.5,22.2,28.6,34.8,41.5,49,58])await run(env.HYPERFRAMES_FFMPEG_PATH!,['-v','error','-y','-ss',String(t),'-i',output,'-frames:v','1',path.join(base,'rendered-'+t+'.png')]);
console.log(JSON.stringify({status:pass?'PASS':'FAIL',output,authorExact,audioExact,duration:media.format.duration}));

const playback=path.join(base,'enhe-studio-editorial-playback-v3-60s.mp4');
await run(env.HYPERFRAMES_FFMPEG_PATH!,['-v','error','-n','-i',output,'-map','0:v:0','-map','0:a:0','-c:v','libx264','-profile:v','high','-pix_fmt','yuv420p','-preset','fast','-crf','12','-c:a','copy','-movflags','+faststart',playback]);
const pp=JSON.parse((await run(env.HYPERFRAMES_FFPROBE_PATH!,['-v','error','-show_streams','-show_format','-of','json',playback])).stdout);
const audioHash=(await run(env.HYPERFRAMES_FFMPEG_PATH!,['-v','error','-i',playback,'-map','0:a:0','-c:a','copy','-f','hash','-hash','sha256','-'])).stdout.trim();
const similarity=await run(env.HYPERFRAMES_FFMPEG_PATH!,['-v','info','-i',output,'-i',playback,'-filter_complex','[0:v]trim=start_frame=1560:end_frame=1800,setpts=PTS-STARTPTS[a];[1:v]trim=start_frame=1560:end_frame=1800,setpts=PTS-STARTPTS[b];[a][b]ssim','-an','-f','null','-']);
await run(env.HYPERFRAMES_FFMPEG_PATH!,['-v','error','-xerror','-i',playback,'-f','null','-']);
await fs.writeFile(path.join(base,'playback-qa.json'),JSON.stringify({path:playback,sha256:digest(await fs.readFile(playback)),media:pp,audioExact:audioHash===exact[0].audioStreamHash,authorSimilarity:similarity.stderr.match(/SSIM[^\n]+/g)?.at(-1),note:'Standard High profile playback derivative. Lossless master preserves original author pixels; this file differs only by video encoding.'},null,2));console.log(JSON.stringify({playback,audioExact:audioHash===exact[0].audioStreamHash}));
